version: "3"
volumes: 
    mongodata:
        driver: local

services: 
    postgres: # airflow
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
    airflow:
        build: .
        image: eugenepy/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
            - mongo
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            # setting For Connection
            - AIRFLOW_CONN_ARCTIC_MONGO=/akira_data:akira_data@mongo:27017
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - /var/run/docker.sock:/var/run/docker.sock # allow docker operator
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "168:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3