version: "3"
services: 
    postgres: # airflow
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes: 
            - airflow_metadata:/var/lib/postgresql/data
    airflow:
        build: .
        image: eugenepy/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
            - mongo
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            # setting For Connection
            - AIRFLOW_CONN_ARCTIC_MONGO=/akira_data:akira_data@mongo:27017
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgres:5432
            - AIRFLOW__CORE__FERNET_KEY=6cLsuD9kKqr70xN5PKlFgJuGahER3DKmWtyseR8dZIA=
            - DOCKER_HOST=tcp://socat:2375
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./docker-airflow/dags:/usr/local/airflow/dags
            - ./docker-airflow/requirements.txt:/requirements.txt
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    socat:
        image: bpack/socat
        command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "2375"

volumes:
    airflow_metadata: